apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-users-pvc
  namespace: hotel-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-hotels-pvc
  namespace: hotel-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-bookings-pvc
  namespace: hotel-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi