# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tishan001/hotel-booking:frontend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: hotel-booking-config
              key: NODE_ENV
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: hotel-booking-config
              key: BASE_URL
        - name: VITE_STRIPE_PUB_KEY
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: VITE_STRIPE_PUB_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hotel-booking
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer