# API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: tishan001/hotel-booking:api-gateway-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        envFrom:
        - configMapRef:
            name: hotel-booking-config
        - secretRef:
            name: hotel-booking-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: hotel-booking
spec:
  selector:
    app: api-gateway
  ports:
  - port: 7000
    targetPort: 7000
  type: LoadBalancer

---
# Auth Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: tishan001/hotel-booking:auth-service-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7001
        envFrom:
        - configMapRef:
            name: hotel-booking-config
        - secretRef:
            name: hotel-booking-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hotel-booking
spec:
  selector:
    app: auth-service
  ports:
  - port: 7001
    targetPort: 7001

---
# User Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: tishan001/hotel-booking:user-service-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7002
        envFrom:
        - configMapRef:
            name: hotel-booking-config
        - secretRef:
            name: hotel-booking-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 7002
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 7002
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: hotel-booking
spec:
  selector:
    app: user-service
  ports:
  - port: 7002
    targetPort: 7002

---
# Hotel Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: tishan001/hotel-booking:hotel-service-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7003
        envFrom:
        - configMapRef:
            name: hotel-booking-config
        - secretRef:
            name: hotel-booking-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"

---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: hotel-booking
spec:
  selector:
    app: hotel-service
  ports:
  - port: 7003
    targetPort: 7003

---
# Booking Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: tishan001/hotel-booking:booking-service-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7004
        envFrom:
        - configMapRef:
            name: hotel-booking-config
        - secretRef:
            name: hotel-booking-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: hotel-booking
spec:
  selector:
    app: booking-service
  ports:
  - port: 7004
    targetPort: 7004

---
# Notifications Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: hotel-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
      - name: notifications-service
        image: tishan001/hotel-booking:notifications-service-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7005
        envFrom:
        - configMapRef:
            name: hotel-booking-config
        - secretRef:
            name: hotel-booking-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: hotel-booking
spec:
  selector:
    app: notifications-service
  ports:
  - port: 7005
    targetPort: 7005