# MongoDB for Users
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-users
  namespace: hotel-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-users
  template:
    metadata:
      labels:
        app: mongo-users
    spec:
      containers:
      - name: mongodb
        image: mongo:7
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: MONGODB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: MONGODB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: users
        volumeMounts:
        - name: mongo-users-storage
          mountPath: /data/db
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mongo-users-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-users
  namespace: hotel-booking
spec:
  selector:
    app: mongo-users
  ports:
  - port: 27017
    targetPort: 27017

---
# MongoDB for Hotels
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-hotels
  namespace: hotel-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-hotels
  template:
    metadata:
      labels:
        app: mongo-hotels
    spec:
      containers:
      - name: mongodb
        image: mongo:7
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: MONGODB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: MONGODB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: hotels
        volumeMounts:
        - name: mongo-hotels-storage
          mountPath: /data/db
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mongo-hotels-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-hotels
  namespace: hotel-booking
spec:
  selector:
    app: mongo-hotels
  ports:
  - port: 27017
    targetPort: 27017

---
# MongoDB for Bookings
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-bookings
  namespace: hotel-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-bookings
  template:
    metadata:
      labels:
        app: mongo-bookings
    spec:
      containers:
      - name: mongodb
        image: mongo:7
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: MONGODB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: MONGODB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: bookings
        volumeMounts:
        - name: mongo-bookings-storage
          mountPath: /data/db
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mongo-bookings-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-bookings
  namespace: hotel-booking
spec:
  selector:
    app: mongo-bookings
  ports:
  - port: 27017
    targetPort: 27017

---
# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: hotel-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: hotel-booking-secrets
              key: RABBITMQ_PASS
        - name: RABBITMQ_DEFAULT_VHOST
          valueFrom:
            configMapKeyRef:
              name: hotel-booking-config
              key: RABBITMQ_DEFAULT_VHOST
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: rabbitmq-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: hotel-booking
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672