name: Build and Push Frontend Docker Image

on:
  push:
    branches: [ main, prod ]
    paths:
      - 'frontend/**'
      - 'frontend/docker-frontend.yml'
  pull_request:
    branches: [ prod ]
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hotel-booking:frontend-latest
        build-args: |
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          VITE_STRIPE_PUB_KEY=${{ secrets.VITE_STRIPE_PUB_KEY }}
          NODE_ENV=production

    - name: Verify pushed image
      run: |
        echo "✅ Successfully built and pushed frontend image:"
        echo "  - frontend-latest"
